export { Navigation } from "./Navigation";
export { Hero } from "./Hero";
export { Services } from "./Services";
export { Work } from "./Work";
export { About } from "./About";
export { Testimonials } from "./Testimonials";
export { Instagram } from "./Instagram";
export { Contact } from "./Contact";
export { Footer } from "./Footer";
